version: 2.1

orbs:
  rust: circleci/rust@1.6.0


jobs:
  build:
    docker:
      - image: cimg/rust:1.58.0
    steps:
      - checkout
      - rust/build:
          with_cache: true

  clippy:
    docker:
      - image: cimg/rust:1.58.0
    steps:
      - checkout
      - rust/clippy:
          with_cache: true

  test:
    docker:
      - image: cimg/rust:1.58.0
    steps:
      - checkout
      - rust/test:
          with_cache: true

  format:
    docker:
      - image: rust
    steps:
      - checkout
      - run: rustup default nightly
      - run: rustup component add rustfmt
      - run: cargo fmt --check


workflows:
  rust:
    jobs:
      - build
      - format
      - clippy:
          requires:
            - build
      - test:
          requires:
            - build
